kind: pipeline
type: docker
name: default
   
steps:
- name: build 
  image: golang:alpine
  network_mode: host
  commands:
  - echo "Running build"
  - go build -o bin/main
  - ./bin/main

- name: ssh commands
  image: appleboy/drone-ssh
  settings:
    host:  
      from_secret: host
    username: 
      from_secret: username
    password: 
      from_secret: password
    port: 22
    script:
      - git clone https://github.com/ikeohachidi/testing-cicd ~/projects
      - docker build -t testing-cicd ~/projects
      - docker run -it -d --restart unless-stopped --name testing-cicd testing-cicd
    
trigger:
  branch:
  - main 